/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tynkrdeebkvcpquorivt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bmtyZGVlYmt2Y3BxdW9yaXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNjAzNzksImV4cCI6MjA5MzgzNjM3OX0.6xK66wwYh-19yEAXiO-XureFDXXPKF4WzLQItoIcM1A"